version: '3.2'
services:
  consul_server:
    image: 192.168.19.252/library/consul:0.8.5
    volumes:
      - /data/swarm_consul:/consul
    labels:
      service: "consul_server" 
    ports:
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host  
    networks:
      - consul
    environment:
      CONSUL_BIND_INTERFACE: "eth0"
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true,"skip_leave_on_interrupt": true}'
    deploy:
      mode: global 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s 
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/ui/"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint:
      -  docker-entrypoint.sh
      -   agent
      -  -server
      -  -datacenter=swarm
      -  -ui
      -  -bootstrap-expect=3
      -  -client=0.0.0.0 
      -  -disable-host-node-id 
      -  -retry-join=consul_server
      -  -retry-join=consul_server
      -  -retry-join=consul_server   
      -  -retry-interval=5s 
      -  -rejoin
  nginx:
    image: 192.168.19.252/library/nginx-consul-template:1.13.2 
    labels:
      service: "proxy_nginx"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host  
    networks:
      - nginx
      - consul
    environment:
      CONSUL_ADDR: consul_server
      CONSUL_PORT: 8500
      IS_HTTPS: 0
      CERT: proxy
    deploy:
      mode: global 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s  
networks:
  nginx:
    driver: overlay   
  consul:
    driver: overlay
